"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CognitiveServicesConfig = exports.WaveHeader = exports.Resampler = exports.MicrophoneAudioSource = exports.WaveFileAudioSource = exports.AudioUtils = exports.AudioSourceWaveStreamer = exports.AudioSource = exports.AudioSink = exports.AudioContextAudioSink = exports.TTSController = exports.NLULanguageCode = exports.NLUController = exports.HotwordController = exports.AsyncToken = exports.ASRController = exports.AzureTTSController = exports.AzureSpeechApiController = exports.AzureSpeechClient = exports.LUISController = void 0;
const LUISController_1 = require("./microsoft/LUISController");
exports.LUISController = LUISController_1.default;
const AzureSpeechClient_1 = require("./microsoft/AzureSpeechClient");
Object.defineProperty(exports, "AzureSpeechClient", { enumerable: true, get: function () { return AzureSpeechClient_1.AzureSpeechClient; } });
const AzureSpeechApiController_1 = require("./microsoft/AzureSpeechApiController");
exports.AzureSpeechApiController = AzureSpeechApiController_1.default;
const AzureTTSController_1 = require("./microsoft/AzureTTSController");
exports.AzureTTSController = AzureTTSController_1.default;
const ASRController_1 = require("./ASRController");
exports.ASRController = ASRController_1.default;
const AsyncToken_1 = require("./AsyncToken");
exports.AsyncToken = AsyncToken_1.default;
const HotwordController_1 = require("./HotwordController");
exports.HotwordController = HotwordController_1.default;
const NLUController_1 = require("./NLUController");
exports.NLUController = NLUController_1.default;
Object.defineProperty(exports, "NLULanguageCode", { enumerable: true, get: function () { return NLUController_1.NLULanguageCode; } });
const TTSController_1 = require("./TTSController");
exports.TTSController = TTSController_1.default;
const AudioContextAudioSink_1 = require("./audio/AudioContextAudioSink");
exports.AudioContextAudioSink = AudioContextAudioSink_1.default;
const AudioSink_1 = require("./audio/AudioSink");
exports.AudioSink = AudioSink_1.default;
const AudioSource_1 = require("./audio/AudioSource");
exports.AudioSource = AudioSource_1.default;
const AudioSourceWaveStreamer_1 = require("./audio/AudioSourceWaveStreamer");
exports.AudioSourceWaveStreamer = AudioSourceWaveStreamer_1.default;
const AudioUtils = require("./audio/AudioUtils");
exports.AudioUtils = AudioUtils;
const WaveFileAudioSource_1 = require("./audio/WaveFileAudioSource");
exports.WaveFileAudioSource = WaveFileAudioSource_1.default;
const MicrophoneAudioSource_1 = require("./audio/MicrophoneAudioSource");
exports.MicrophoneAudioSource = MicrophoneAudioSource_1.default;
const Resampler_1 = require("./audio/Resampler");
exports.Resampler = Resampler_1.default;
const WaveHeader_1 = require("./audio/WaveHeader");
exports.WaveHeader = WaveHeader_1.default;
const CognitiveServicesConfig_1 = require("./CognitiveServicesConfig");
exports.CognitiveServicesConfig = CognitiveServicesConfig_1.default;
//# sourceMappingURL=index.js.map